# Generated by Django 3.2.7 on 2021-09-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='username',
        ),
    ]
