# Generated by Django 3.2.7 on 2021-09-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApi', '0002_rename_user_cart_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='user',
        ),
    ]
